{{- if not .Values.appSecret.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "taskmanager.fullname" . }}
  labels:
    {{- include "taskmanager.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.appSecret.key }}: {{ include "taskmanager.secretKey" . }}
{{- end }}
